# Site settings
title: Lucas F. Costa
full_name: Lucas F. Costa
email: lucas@lucasfcosta.com
description: Software engineering, culture and life in general.
subtitle: Human thoughts about exact sciences
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://lucasfcosta.com" # the base hostname & protocol for your site
github_username: lucasfcosta
linkedin_username: lucasfdacosta
twitter_username: thewizardlucas

# Collections
collections:
  talks:
    output: true
  reveries:
    output: true

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
katex:
  js_path: "{{ Gem::lib_path }}/assets/js" # Path used to search for katex.min.js
timezone: Europe/London
plugins: [jekyll-paginate, jekyll-assets, jekyll-katex]
